[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ytaedl"
version = "0.3.0"
description = "A modular and concurrent downloader for YouTube, AEBN, and more."
readme = "README.md"
requires-python = ">=3.8"

[project.scripts]
yt-ae-dl = "ytaedl.cli:main"
ytaedl   = "ytaedl.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["ytaedl*", "ytaedl*"]

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-asyncio",
  "pytest-cov",
  "mock",
  "libtmux",
]
