[build-system]
requires = [ "setuptools>=64",]
build-backend = "setuptools.build_meta"

[project]
name = "parallel_runner"
version = "0.1.0"
requires-python = ">=3.6"
dependencies = [ "rich",]
[[project.authors]]

[tool.setuptools.packages.find]
